#define __STDC__ 1
#define __STDC_VERSION__ 199409L
#define __EDG__ 1
#define __EDG_VERSION__ 407
#define __EDG_SIZE_TYPE__ unsigned int
#define __EDG_PTRDIFF_TYPE__ int
#define __sizeof_int 4
#define __sizeof_long 4
#define __sizeof_ptr 4
#define __ARMCC_VERSION 5060750
#define __TARGET_CPU_CORTEX_M0 1
#define __TARGET_FPU_SOFTVFP 1
#define __MICROLIB 1
#define __UVISION_VERSION 530
#define _RTE_ 1
#define __CC_ARM 1
#define __arm 1
#define __arm__ 1
#define __TARGET_ARCH_6S_M 1
#define __TARGET_ARCH_ARM 0
#define __TARGET_ARCH_THUMB 3
#define __TARGET_ARCH_A64 0
#define __TARGET_ARCH_AARCH32 1
#define __TARGET_PROFILE_M 1
#define __TARGET_FEATURE_HALFWORD 1
#define __TARGET_FEATURE_THUMB 1
#define __TARGET_FEATURE_DMB 1
#define __TARGET_FEATURE_EXTENSION_REGISTER_COUNT 0
#define __APCS_INTERWORK 1
#define __thumb 1
#define __thumb__ 1
#define __t32__ 1
#define __OPTIMISE_SPACE 1
#define __OPT_SMALL_ASSERT 1
#define __OPTIMISE_LEVEL 2
#define __SOFTFP__ 1
